'use strict';
module.exports = {
  up: async (queryInterface, Sequelize) => queryInterface.bulkInsert('users',
    [
      {
        name: 'John Doe',
        genro: 'female',
        email: 'john.doe@example.com',
        password: 'password123',
        image: 'https://example.com/john.jpg',
        relationship: 'single',
        interesting: 'female',
        country: 'USA',
        city: 'New York',
        work: 'Software Engineer',
        education: 'Bachelor of Science',
        age: '25-35',
        phone_number: '123-456-7890',
        birthdate: '1990-01-01',
        bio: 'A passionate software engineer who loves coding and problem-solving.',
        hobbies: 'coding, hiking, reading',
        favorite_movies: 'Inception, The Matrix',
        favorite_books: '1984, Brave New World',
        favorite_music: 'Rock, Jazz',
        language: 'English',
        favorite_food: 'Rice',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'Jane Smith',
        genro: 'female',
        email: 'jane.smith@example.com',
        password: 'password123',
        image: 'https://example.com/jane.jpg',
        relationship: 'single',
        interesting: 'female',
        country: 'USA',
        city: 'New York',
        work: 'Software Engineer',
        education: 'Bachelor of Science',
        age: '25-35',
        phone_number: '987-654-3210',
        birthdate: '1992-02-02',
        bio: 'An enthusiastic software developer with a love for technology.',
        hobbies: 'photography, traveling, painting',
        favorite_movies: 'The Godfather, Pulp Fiction',
        favorite_books: 'To Kill a Mockingbird, The Great Gatsby',
        favorite_music: 'Pop, Classical',
        language: 'English',
        favorite_food: 'Rice',
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        name: 'Alice Johnson',
        genro: 'female',
        email: 'alice.johnson@example.com',
        password: 'password123',
        image: 'https://example.com/alice.jpg',
        relationship: 'single',
        interesting: 'female',
        country: 'USA',
        city: 'New York',
        work: 'Software Engineer',
        education: 'Bachelor of Science',
        age: '25-35',
        phone_number: '555-123-4567',
        birthdate: '1991-03-03',
        bio: 'A creative and analytical software engineer.',
        hobbies: 'gaming, cooking, gardening',
        favorite_movies: 'Avatar, Interstellar',
        favorite_books: 'The Catcher in the Rye, The Lord of the Rings',
        favorite_music: 'Hip-Hop, Blues',
        favorite_food: 'Rice',
        language: 'English',
        created_at: new Date(),
        updated_at: new Date()
      }
    ], {}),

  down: async (queryInterface) => queryInterface.bulkDelete('users', null, {}),
};
